package org.chama.domain.enums;

public enum ActivityEventType {
    MEMBER_INVITED,
    CONTRIBUTION_PAID,
    LOAN_APPROVED,
    PAYOUT_DISBURSED,
    DOCUMENT_GENERATED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    AGM_STATEMENT_GENERATED,
    RESOLUTION_OPENED,
    RESOLUTION_CLOSED,
    WELFARE_CONTRIBUTION_PAID,
    WELFARE_FUND_WITHDRAWN,
    LOAN_REJECTED,
    AUTO_STK_PUSH_SENT,
}
