package org.chama.dto;

import jakarta.validation.constraints.NotNull;
import org.chama.domain.enums.RotationOrderType;

import java.util.List;

/**
 * {@code agreedMemberIds} is required and gives the explicit rotation order
 * when {@code rotationOrderType} is AGREED; ignored (may be null) for RANDOM
 * and SENIORITY, where the order is generated by the service instead.
 */
public record GeneratePayoutScheduleDto(
    @NotNull RotationOrderType rotationOrderType,
    List<Long> agreedMemberIds) {
}
