package org.chama.service;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import jakarta.enterprise.context.ApplicationScoped;
import org.chama.domain.enums.DocumentType;
import org.chama.dto.DocumentLineItemDto;
import org.jboss.logging.Logger;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Renders a GeneratedDocument's PDF bytes with OpenPDF, ported from DondooHomes'
 * UniversalPdfDocumentService. One shared layout covers all three document types (contribution
 * receipt, loan statement, payout receipt), they only differ in title and line items, unlike
 * DondooHomes' invoice/receipt split which needed genuinely different layouts.
 */
@ApplicationScoped
public class PdfDocumentService {

    private static final Logger LOG = Logger.getLogger(PdfDocumentService.class);
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("d MMMM yyyy");

    // Mirrors frontend/tailwind.config.js, keep these in sync with the design tokens.
    private static final Color PRIMARY = new Color(0x3D, 0x3A, 0x6B);
    private static final Color INK = new Color(0x1C, 0x1A, 0x17);
    private static final Color MUTED = new Color(0x6E, 0x67, 0x59);
    private static final Color PAPER_DIM = new Color(0xF2, 0xEB, 0xD9);

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 20, Font.BOLD, PRIMARY);
    private static final Font BRAND_FONT = new Font(Font.HELVETICA, 14, Font.BOLD, INK);
    private static final Font LABEL_FONT = new Font(Font.HELVETICA, 9, Font.NORMAL, MUTED);
    private static final Font VALUE_FONT = new Font(Font.HELVETICA, 11, Font.NORMAL, INK);
    private static final Font TABLE_HEADER_FONT = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);
    private static final Font TABLE_CELL_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL, INK);
    private static final Font TOTAL_FONT = new Font(Font.HELVETICA, 13, Font.BOLD, PRIMARY);
    private static final Font FOOTER_FONT = new Font(Font.HELVETICA, 8, Font.ITALIC, MUTED);

    public byte[] render(DocumentType type, String documentNumber, String chamaName, String memberName,
            LocalDate issueDate, List<DocumentLineItemDto> lineItems, BigDecimal totalAmount,
            String billingPeriod, String notes) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            Document document = new Document(PageSize.A4, 48, 48, 56, 56);
            PdfWriter.getInstance(document, out);
            document.open();

            document.add(header(chamaName, title(type)));
            document.add(Chunk.NEWLINE);
            document.add(metaTable(documentNumber, issueDate, billingPeriod));
            document.add(Chunk.NEWLINE);
            document.add(recipient(memberName));
            document.add(Chunk.NEWLINE);
            document.add(lineItemsTable(lineItems, totalAmount));

            if (notes != null && !notes.isBlank()) {
                document.add(Chunk.NEWLINE);
                Paragraph notesParagraph = new Paragraph(notes, VALUE_FONT);
                notesParagraph.setSpacingBefore(8);
                document.add(notesParagraph);
            }

            document.add(Chunk.NEWLINE);
            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("Generated by Webchama, this is a system-generated document.", FOOTER_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
        } catch (DocumentException e) {
            LOG.error("PDF generation failed for " + documentNumber, e);
            throw new IllegalStateException("PDF generation failed", e);
        }
        return out.toByteArray();
    }

    private String title(DocumentType type) {
        return switch (type) {
            case CONTRIBUTION_RECEIPT -> "CONTRIBUTION RECEIPT";
            case LOAN_STATEMENT -> "LOAN STATEMENT";
            case PAYOUT_RECEIPT -> "PAYOUT RECEIPT";
        };
    }

    private PdfPTable header(String chamaName, String title) throws DocumentException {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1, 1});

        PdfPCell brandCell = new PdfPCell(new Paragraph(chamaName, BRAND_FONT));
        brandCell.setBorder(0);
        brandCell.setPaddingBottom(4);
        table.addCell(brandCell);

        PdfPCell titleCell = new PdfPCell(new Paragraph(title, TITLE_FONT));
        titleCell.setBorder(0);
        titleCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        table.addCell(titleCell);

        PdfPCell ruleCell = new PdfPCell();
        ruleCell.setColspan(2);
        ruleCell.setFixedHeight(2f);
        ruleCell.setBackgroundColor(PRIMARY);
        ruleCell.setBorder(0);
        table.addCell(ruleCell);

        return table;
    }

    private PdfPTable metaTable(String documentNumber, LocalDate issueDate, String billingPeriod) {
        PdfPTable table = new PdfPTable(billingPeriod != null ? 3 : 2);
        table.setWidthPercentage(100);

        addMetaCell(table, "DOCUMENT NUMBER", documentNumber);
        addMetaCell(table, "DATE", issueDate.format(DATE_FORMAT));
        if (billingPeriod != null) {
            addMetaCell(table, "PERIOD", billingPeriod);
        }
        return table;
    }

    private void addMetaCell(PdfPTable table, String label, String value) {
        Paragraph paragraph = new Paragraph();
        paragraph.add(new Chunk(label + "\n", LABEL_FONT));
        paragraph.add(new Chunk(value, VALUE_FONT));
        PdfPCell cell = new PdfPCell(paragraph);
        cell.setBorder(0);
        cell.setPaddingBottom(8);
        table.addCell(cell);
    }

    private Paragraph recipient(String memberName) {
        Paragraph paragraph = new Paragraph();
        paragraph.add(new Chunk("ISSUED TO\n", LABEL_FONT));
        paragraph.add(new Chunk(memberName, VALUE_FONT));
        return paragraph;
    }

    private PdfPTable lineItemsTable(List<DocumentLineItemDto> lineItems, BigDecimal totalAmount) {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3, 1});
        table.setSpacingBefore(4);

        table.addCell(headerCell("DESCRIPTION"));
        table.addCell(headerCell("AMOUNT (KES)"));

        for (DocumentLineItemDto item : lineItems) {
            PdfPCell descCell = new PdfPCell(new Paragraph(item.description(), TABLE_CELL_FONT));
            descCell.setPadding(6);
            table.addCell(descCell);

            PdfPCell amountCell = new PdfPCell(new Paragraph(formatAmount(item.amount()), TABLE_CELL_FONT));
            amountCell.setPadding(6);
            amountCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            table.addCell(amountCell);
        }

        PdfPCell totalLabelCell = new PdfPCell(new Paragraph("TOTAL", TOTAL_FONT));
        totalLabelCell.setBorder(PdfPCell.TOP);
        totalLabelCell.setPadding(6);
        totalLabelCell.setBackgroundColor(PAPER_DIM);
        table.addCell(totalLabelCell);

        PdfPCell totalValueCell = new PdfPCell(new Paragraph(formatAmount(totalAmount), TOTAL_FONT));
        totalValueCell.setBorder(PdfPCell.TOP);
        totalValueCell.setPadding(6);
        totalValueCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        totalValueCell.setBackgroundColor(PAPER_DIM);
        table.addCell(totalValueCell);

        return table;
    }

    private PdfPCell headerCell(String text) {
        PdfPCell cell = new PdfPCell(new Paragraph(text, TABLE_HEADER_FONT));
        cell.setBackgroundColor(PRIMARY);
        cell.setPadding(6);
        return cell;
    }

    private String formatAmount(BigDecimal amount) {
        return String.format("%,.2f", amount);
    }
}
